Traceback (most recent call last):
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\henry\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Crear mapa coroplÃ©tico
fig = px.choropleth(df_municipios,
                    geojson=colombia_geojson,
                    locations='MUNICIPIO',
                    featureidkey="properties.NOMBRE_DPT",
                    color='COUNT',
                    color_continuous_scale="Reds",
                    title="DistribuciÃ³n de Defunciones por Municipio en Colombia",
                    labels={'COUNT': 'NÃºmero de Registros'}
                   )

# Ajustar el diseÃ±o del mapa
fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(template='plotly_white')

# Mostrar mapa
fig.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn[52], line 2[0m
[0;32m      1[0m [38;5;66;03m# Crear mapa coroplÃ©tico[39;00m
[1;32m----> 2[0m fig [38;5;241m=[39m [43mpx[49m[38;5;241;43m.[39;49m[43mchoropleth[49m[43m([49m[43mdf_municipios[49m[43m,[49m
[0;32m      3[0m [43m                    [49m[43mgeojson[49m[38;5;241;43m=[39;49m[43mcolombia_geojson[49m[43m,[49m
[0;32m      4[0m [43m                    [49m[43mlocations[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mMUNICIPIO[39;49m[38;5;124;43m'[39;49m[43m,[49m
[0;32m      5[0m [43m                    [49m[43mfeatureidkey[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mproperties.NOMBRE_DPT[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m      6[0m [43m                    [49m[43mcolor[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mCOUNT[39;49m[38;5;124;43m'[39;49m[43m,[49m
[0;32m      7[0m [43m                    [49m[43mcolor_continuous_scale[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mReds[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m      8[0m [43m                    [49m[43mtitle[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mDistribuciÃ³n de Defunciones por Municipio en Colombia[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m      9[0m [43m                    [49m[43mlabels[49m[38;5;241;43m=[39;49m[43m{[49m[38;5;124;43m'[39;49m[38;5;124;43mCOUNT[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mNÃºmero de Registros[39;49m[38;5;124;43m'[39;49m[43m}[49m
[0;32m     10[0m [43m                   [49m[43m)[49m
[0;32m     12[0m [38;5;66;03m# Ajustar el diseÃ±o del mapa[39;00m
[0;32m     13[0m fig[38;5;241m.[39mupdate_geos(fitbounds[38;5;241m=[39m[38;5;124m"[39m[38;5;124mlocations[39m[38;5;124m"[39m, visible[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\plotly\express\_chart_types.py:1113[0m, in [0;36mchoropleth[1;34m(data_frame, lat, lon, locations, locationmode, geojson, featureidkey, color, facet_row, facet_col, facet_col_wrap, facet_row_spacing, facet_col_spacing, hover_name, hover_data, custom_data, animation_frame, animation_group, category_orders, labels, color_discrete_sequence, color_discrete_map, color_continuous_scale, range_color, color_continuous_midpoint, projection, scope, center, fitbounds, basemap_visible, title, subtitle, template, width, height)[0m
[0;32m   1072[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mchoropleth[39m(
[0;32m   1073[0m     data_frame[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m   1074[0m     lat[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m   (...)[0m
[0;32m   1107[0m     height[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m   1108[0m ) [38;5;241m-[39m[38;5;241m>[39m go[38;5;241m.[39mFigure:
[0;32m   1109[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m   1110[0m [38;5;124;03m    In a choropleth map, each row of `data_frame` is represented by a[39;00m
[0;32m   1111[0m [38;5;124;03m    colored region mark on a map.[39;00m
[0;32m   1112[0m [38;5;124;03m    """[39;00m
[1;32m-> 1113[0m     [38;5;28;01mreturn[39;00m [43mmake_figure[49m[43m([49m
[0;32m   1114[0m [43m        [49m[43margs[49m[38;5;241;43m=[39;49m[38;5;28;43mlocals[39;49m[43m([49m[43m)[49m[43m,[49m
[0;32m   1115[0m [43m        [49m[43mconstructor[49m[38;5;241;43m=[39;49m[43mgo[49m[38;5;241;43m.[39;49m[43mChoropleth[49m[43m,[49m
[0;32m   1116[0m [43m        [49m[43mtrace_patch[49m[38;5;241;43m=[39;49m[38;5;28;43mdict[39;49m[43m([49m[43mlocationmode[49m[38;5;241;43m=[39;49m[43mlocationmode[49m[43m)[49m[43m,[49m
[0;32m   1117[0m [43m    [49m[43m)[49m

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\plotly\express\_core.py:2477[0m, in [0;36mmake_figure[1;34m(args, constructor, trace_patch, layout_patch)[0m
[0;32m   2474[0m layout_patch [38;5;241m=[39m layout_patch [38;5;129;01mor[39;00m {}
[0;32m   2475[0m apply_default_cascade(args)
[1;32m-> 2477[0m args [38;5;241m=[39m [43mbuild_dataframe[49m[43m([49m[43margs[49m[43m,[49m[43m [49m[43mconstructor[49m[43m)[49m
[0;32m   2478[0m [38;5;28;01mif[39;00m constructor [38;5;129;01min[39;00m [go[38;5;241m.[39mTreemap, go[38;5;241m.[39mSunburst, go[38;5;241m.[39mIcicle] [38;5;129;01mand[39;00m args[[38;5;124m"[39m[38;5;124mpath[39m[38;5;124m"[39m] [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m   2479[0m     args [38;5;241m=[39m process_dataframe_hierarchy(args)

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\plotly\express\_core.py:1727[0m, in [0;36mbuild_dataframe[1;34m(args, constructor)[0m
[0;32m   1724[0m     args[[38;5;124m"[39m[38;5;124mcolor[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28;01mNone[39;00m
[0;32m   1725[0m [38;5;66;03m# now that things have been prepped, we do the systematic rewriting of `args`[39;00m
[1;32m-> 1727[0m df_output, wide_id_vars [38;5;241m=[39m [43mprocess_args_into_dataframe[49m[43m([49m
[0;32m   1728[0m [43m    [49m[43margs[49m[43m,[49m
[0;32m   1729[0m [43m    [49m[43mwide_mode[49m[43m,[49m
[0;32m   1730[0m [43m    [49m[43mvar_name[49m[43m,[49m
[0;32m   1731[0m [43m    [49m[43mvalue_name[49m[43m,[49m
[0;32m   1732[0m [43m    [49m[43mis_pd_like[49m[43m,[49m
[0;32m   1733[0m [43m    [49m[43mnative_namespace[49m[43m,[49m
[0;32m   1734[0m [43m[49m[43m)[49m
[0;32m   1735[0m df_output: nw[38;5;241m.[39mDataFrame
[0;32m   1736[0m [38;5;66;03m# now that `df_output` exists and `args` contains only references, we complete[39;00m
[0;32m   1737[0m [38;5;66;03m# the special-case and wide-mode handling by further rewriting args and/or mutating[39;00m
[0;32m   1738[0m [38;5;66;03m# df_output[39;00m

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\plotly\express\_core.py:1328[0m, in [0;36mprocess_args_into_dataframe[1;34m(args, wide_mode, var_name, value_name, is_pd_like, native_namespace)[0m
[0;32m   1326[0m         [38;5;28;01mif[39;00m argument [38;5;241m==[39m [38;5;124m"[39m[38;5;124mindex[39m[38;5;124m"[39m:
[0;32m   1327[0m             err_msg [38;5;241m+[39m[38;5;241m=[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m To use the index, pass it in directly as `df.index`.[39m[38;5;124m"[39m
[1;32m-> 1328[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(err_msg)
[0;32m   1329[0m [38;5;28;01melif[39;00m length [38;5;129;01mand[39;00m (actual_len [38;5;241m:=[39m [38;5;28mlen[39m(df_input)) [38;5;241m!=[39m length:
[0;32m   1330[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m   1331[0m         [38;5;124m"[39m[38;5;124mAll arguments should have the same length. [39m[38;5;124m"[39m
[0;32m   1332[0m         [38;5;124m"[39m[38;5;124mThe length of column argument `df[[39m[38;5;132;01m%s[39;00m[38;5;124m]` is [39m[38;5;132;01m%d[39;00m[38;5;124m, whereas the [39m[38;5;124m"[39m
[1;32m   (...)[0m
[0;32m   1339[0m         )
[0;32m   1340[0m     )

[1;31mValueError[0m: Value of 'locations' is not the name of a column in 'data_frame'. Expected one of ['municipio', 'casos'] but received: MUNICIPIO

